### ISSUE TITLE
Appveyor reports success when the build fails

### ISSUE THREAD

**Issue by adamralph** [blairconrad/SelfInitializingFakes#60]
![image](https://user-images.githubusercontent.com/677704/44954571-344aff80-aea4-11e8-9d7a-039f910fb821.png)

**Comment by adamralph** [comment]
Looks like a problem in Appveryor. I've raised https://help.appveyor.com/discussions/problems/16519-failure-in-ps1-script-results-in-successful-build

In the meantime, #65 works around the problem.

**Comment by blairconrad** [comment]
Hey, @adamralph. Thanks for your continued interest in this. I've subscribed to your appveyor issue.

**Comment by blairconrad** [comment]
Thanks, @adamralph. This change was "released" in 0.4.0.
Check for your name in the [release notes](https://github.com/blairconrad/SelfInitializingFakes/releases/tag/0.4.0)! 🏗️
